#handle grabled
export LC_ALL=zh_CN.UTF-8
export LANG=zh_CN.UTF-8
export PATH
export PATH="/usr/local/opt/lsof/bin:$PATH"
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

if [ -f ~/.git-completion.bash ]; then
   . ~/.git-completion.bash
fi
